version: "3.7"

x-common:
  &common-settings
  build:
    context: .
    dockerfile: docker/Dockerfile
  restart: always

services:
  web:
    << : *common-settings
    command: dumb-init bash -c "(bundle check || bundle install) && puma -p 3000 -C config/puma.rb"
    networks:
      - backend
    ports:
      - "3000:3000"

networks:
  backend:
    external: true
